# Generated by Django 3.2.6 on 2021-11-13 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_auto_20211113_1620'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='tags',
            field=models.ManyToManyField(related_name='tags', through='recipes.RecipeTags', to='recipes.Tag', verbose_name='Теги, используемые для рецепта'),
        ),
    ]
